name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Prepare Release
      run: echo "RELEASE_VERSION=$(cat ExcelAD.csproj | grep -o '<Version>.*</Version>' | grep -o '[0-9\.]*')" >> $env:GITHUB_ENV

    - name: Create Release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.RELEASE_VERSION,
              tag_name: `v${process.env.RELEASE_VERSION}`,
              draft: true,
            });

            console.log(JSON.stringify(response))

            const fs = require("fs");
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: response.data.id,
              name: "ExcelAD-AddIn64-packed.xll",
              data: fs.readFileSync("./bin/Release/net6.0-windows/publish/ExcelAD-AddIn64-packed.xll"),
            });

          } catch (error) {
            core.setFailed(error.message);
          }