name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false

    - run: echo "RELEASE_VERSION=$(cat ExcelAD.csproj | grep -o '<Version>.*</Version>' | grep -o '[0-9\.]*')" >> $GITHUB_ENV

    - name: Create release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const response = await github.rest.repos.createRelease({
              draft: true,
              name: process.env.RELEASE_VERSION,
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.RELEASE_VERSION,
            });

          } catch (error) {
            core.setFailed(error.message);
          }